config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable do
      resources :answers, only: %i[create destroy edit update]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root 'pages#index'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Authorship
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 5 }

  scope :all_by_tags, lambda { |tags|
    questions = includes(:user)
    questions = if tags
                  questions.joins(:tags).where(tags: tags).preload(:tags)
                else
                  questions.includes(:question_tags, :tags)
                end

    questions.order(created_at: :desc)
  }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include QuestionsAnswers
  before_action :require_authentication, except: %i[show index]
  before_action :set_question, only: %i[show edit update destroy]
  before_action :authorize_question!
  after_action :verify_authorized

  def index
    @tags = Tag.where(id: params[:tag_ids]) if params[:tag_ids]
    @pagy, @questions = pagy Question.all_by_tags(@tags), link_extra: 'data-turbo-frame="pagination_pagy"'
    @questions = @questions.decorate
  end

  def show
    load_questions_answers
  end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = current_user.questions.build question_params
    if @question.save
      respond_to do |format|
        format.html do
          flash[:success] = 'Question successfully created!'
          redirect_to questions_path
        end

        format.turbo_stream do
          @question = @question.decorate
          flash.now[:success] = 'Question successfully created!'
        end
      end
    else
      render :new
    end
  end

  def update
    if @question.update question_params
      respond_to do |format|
        format.html do
          flash[:success] = 'Question successfully updated'
          redirect_to questions_path
        end

        format.turbo_stream do
          @question = @question.decorate
          flash.now[:success] = 'Question successfully updated!'
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html do
        flash[:success] = t('.success')
        redirect_to questions_path
      end

      format.turbo_stream do
        flash.now[:success] = t('.success')
      end
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, tag_ids: [])
  end

  def set_question
    @question = Question.find params[:id]
  end

  def authorize_question!
    authorize(@question || Question)
  end
end

app/views/questions/_form.html.erb
<%= turbo_frame_tag @question do %>
  <%= form_with model: @question do |f| %>
    <%= render 'shared/errors', object: @question %>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title %>
      </div>

      <div class="col-sm-10">
        <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :body %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :body, class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :tags %>
      </div>

      <div class="col-sm-10">
        <%= f.collection_select :tag_ids, @question.tags, :id, :title, {}, multiple: true,
                                class: 'js-multiple-select js-ajax-select w-100', data: {'ajax-url': '/api/tags'} %>
      </div>
    </div>

    <%= f.submit "Submit question!", class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/questions/_question.html.erb
<%= turbo_frame_tag question do %>
  <article class="card mt-3">
    <section class="card-header">
      <%= question.user.gravatar %>
      <%= question.user.name_or_email %>
    </section>

    <div class="card-body">
      <h2><%= link_to question.title, question_path(question), data: { turbo_frame: '_top' } %></h2>

        <section class="card-text">
          <time datetime="<%= question.formatted_created_at %>">
            <small><%= question.formatted_created_at %></small>
          </time>

          <div class="my-2">
            <%= render question.tags %>
          </div>

          <p class="my-2">
            <%= sanitize question.body %>
          </p>
        </section>

        <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %>

        <% if policy(question).edit? %>
          <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %>
        <% end %>

        <% if policy(question).destroy? %>
          <%= link_to 'Destroy', question_path(question), class: 'btn btn-danger',
                      data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
        <% end %>
    </div>
  </article>
<% end %>

app/views/questions/create.turbo_stream.erb
<%= turbo_stream.prepend 'questions', render(@question) %>
<%= prepend_flash %>

app/views/questions/destroy.turbo_stream.erb
<%= turbo_stream.remove @question %>
<%= prepend_flash %>

app/views/questions/edit.html.erb
<% provide :page_title, 'Edit question' %>
<% currently_at 'Edit question' %>


<h1 class="mb-4">Edit question:</h1>

<%= render 'form', tags: @tags %>

app/views/questions/index.html.erb
<% provide :page_title, t('menu.questions') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4">Questions</h1>

<section class="mb-5">
  <h2><%= t '.search_by_tags' %></h2>

  <%= form_with url: questions_path, method: :get do |f| %>
    <div class="mb-3">
      <%= f.collection_select :tag_ids, (@tags || []), :id, :title, {selected: params[:tag_ids]},
          multiple: true, required: true,
          class: 'js-multiple-select js-ajax-select w-100', data: {'ajax-url': '/api/tags'} %>
    </div>

    <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
  <% end %>
</section>

<% if policy(:question).new? %>
  <%= link_to 'New question', new_question_path,
              class: 'btn btn-primary btn-lg mb-3',
              data: { turbo_frame: dom_id(Question.new) }%>

  <div class="my-3">
    <%= turbo_frame_tag Question.new %>
  </div>
<% end %>


<%= turbo_frame_tag 'pagination_pagy' do %>
  <%== pagy_bootstrap_nav @pagy %>

  <%= turbo_frame_tag 'questions' do %>
    <%= render @questions %>
  <% end %>

  <%== pagy_bootstrap_nav @pagy %>
<% end %>

app/views/questions/new.html.erb
<% provide :page_title, 'New question' %>
<% currently_at 'Questions' %>

<h1>New question</h1>

<%= render 'form', tags: @tags %>

app/views/questions/show.html.erb
<% currently_at %>

<%= render @question %>

<%= render 'comments/commentable', commentable: @question, comment: @comment %>

<h2>Write your answer:</h2>

<%= render 'answers/form' %>

<h2 class="mt-5 mb-3">Answers:</h2>

<%== pagination @pagy %>

<%= turbo_frame_tag 'answers' do %>
  <%= render partial: 'answers/answer', collection: @answers,
             as: :answer, locals: {question: @question} %>
<% end %>

<%== pagination @pagy %>

app/views/questions/update.turbo_stream.erb
<%= turbo_stream.replace @question, render(@question) %>
<%= prepend_flash %>